repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: debug-statements
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: isort
        name: sort imports
        description: ensure that imports are sorted in alphabetical order.
        entry: isort
        language: system
        types: [python]
      - id: camel-to-snake-fixer
        name: convert camelCase to snake_case (python)
        description: convert camelCase identifiers, excluding class and function names, to snake_case.
        entry: python3 pre_commit_hooks/camel_to_snake_fixer.py
        language: system
        types: [python]
        exclude: "pre_commit_hooks/camel_to_snake_fixer.py"
